### ISSUE TITLE
💔 Gateway ws channels become disconnected

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#132]
# Handle panic in kafka-io

We should recover from panic cases in Kafka io nested error. See comment below 

# Handle channel disconnects 

We may need to recover from channel disconnects in several places:

- Kafka IO recv
- router command send 
- ?? 

## Detail 

See https://docs.rs/crossbeam/0.7.3/crossbeam/channel/index.html#disconnection

```text
🎫 2ac1507e          OPEN
🤝 2ac1507e          FINDPUBG
😠 2ac1507e          ERROR    sending router command to add client sending on a disconnected channel
🗳 2ac1507e          CHSCLRPF
🏓 2ac1507e          PINGPONG 81ms
```

This happens at `websocket.rs` around L229

```rs
if let Err(e) = self.router_commands_in.send(RouterCommand::AddClient {
                        client_id: self.client_id,
                        events_in,
                    }) {
                        println!(
                            "😠 {} {:<8} sending router command to add client {}",
                            session_code(self),
                            "ERROR",
                            e
                        )
                    }
```

This ultimately prevents communication back to the browser.

**Comment by Terkwood** [comment]
```text
thread '<unnamed>' panicked at 'Nested error (!) waiting on kafka stream: KafkaError (Message consumption error: GroupLoadInProgress (Broker: Group coordinator load in progress))', src/kafka_io.rs:111:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'Unable to receive kafka event via router channel: RecvError', src/router.rs:275:29
🎫 b267b935          OPEN
🤝 b267b935          FINDPUBG
😠 b267b935          ERROR    sending router command to add client sending on a disconnected channel
🗳 b267b935          CHSCLRPF
```

**Comment by Terkwood** [comment]
```
🏓 f5a807cd aee312ef PINGPONG 115ms
🏓 ad3b0bfb aee312ef PINGPONG 122ms
🚪 ad3b0bfb aee312ef CLOSE    Away
🗑                   CLEANUP  1    entries
🤖 f5a807cd aee312ef BEEP
🏓 f5a807cd aee312ef PINGPONG 99ms
🚪 f5a807cd aee312ef CLOSE    Away
thread '<unnamed>' panicked at 'Nested error (!) waiting on kafka stream: KafkaError (Message consumption error: BrokerTransportFailure (Local: Broker transport failure))', src/kafka_io.rs:111:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'Unable to receive kafka event via router channel: RecvError', src/router.rs:275:29
🎫 9f7ab8be          OPEN
🤝 9f7ab8be          FINDPUBG
😠 9f7ab8be          ERROR    sending router command to add client sending on a disconnected channel
🗳 9f7ab8be          CHSCLRPF
```

**Comment by Terkwood** [comment]
Related to #75. This is easily triggered by letting the big box shutdown, and then restarting it. It doesn't happen every time

**Comment by Terkwood** [comment]
Crossbeam channel becomes disconnected. We should have a process which can reallocate such channels and hand them off (delivering the channel endpoints over channels, naturally!)

**Comment by Terkwood** [comment]
https://docs.rs/crossbeam/0.7.3/crossbeam/channel/index.html#disconnection

**Comment by Terkwood** [comment]
One instance here

Websocket.rs
```
                "😠 {} {:<8} sending router command to add client {}",
```

**Comment by Terkwood** [comment]
https://github.com/Terkwood/BUGOUT/blob/ebc1004d7dbf6dab5d929ef526b23750cec2b201/gateway/src/kafka_io.rs#L125

Maybe just try removing the `panic!()`

**Comment by Terkwood** [comment]
potentially related 
```
err in idle recv for kafka
...HALP err on recv shutdown...
...HALP err on recv shutdown...
...HALP err on recv shutdown...
...HALP err on recv shutdown...
...HALP err on recv shutdown...
err in idle recv for kafka
```

**Comment by Terkwood** [comment]
See #143, which removes some explicit `panic!` calls
