### ISSUE TITLE
Judge: Guard against null gamestate in join

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#22]
If you send a MakeMoveCmd but there is no gamestate available to join:

```txt
judge_1                  | MAKE MOVE CMD 00b8d848 BLACK Coord(x=0, y=18)
judge_1                  | Exception in thread "bugout-judge-3474fb5f-ef9f-4a9f-b82d-7234a7120d44-StreamThread-1" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method Judge$process$valueJoiner$1.apply, parameter rightValue
judge_1                  | 	at Judge$process$valueJoiner$1.apply(Judge.kt)
judge_1                  | 	at Judge$process$valueJoiner$1.apply(Judge.kt:18)
judge_1                  | 	at org.apache.kafka.streams.kstream.internals.KStreamKTableJoinProcessor.process(KStreamKTableJoinProcessor.java:73)
judge_1                  | 	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117)
```

**Comment by Terkwood** [comment]
A simple way to deal with this is to have the gateway enforce that an empty game record will always be produced to changelog, before any move command

**Comment by Terkwood** [comment]
Use an inner join instead of a left join

https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Streams+Join+Semantics
