### ISSUE TITLE
💸 Automatic startup and shutdown for Kafka host 

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#75]
# The Big Picture: Run BUGOUT at Very Low Cost

Let's run BUGOUT at a very low cost, relying mostly on a micro instance to support gateway and the reverse proxy, and starting/stopping the larger JVM services as necessary.

## status 

Big box starts up cleanly on a t2.medium. Runs Kafka and JVM apps. Reaper is implemented. Need to add startup service (bugle) 📯 

### todo

- udp channel between bugle and gateway 
- gateway listen for message on shutdown channel

## initial Grand plan

Provides low AWS cost, uses a single micro instance at all times.

- gateway lives on its own micro instance
- gateway micro instance uses a perm DNS address
- kafka / judge / changelog box is turned off when it isn't needed (see DEAD ZONE MONITOR, below)
- gateway would need to know how to disconnect from kafka gracefully, when kafka goes down
- DEAD ZONE MONITOR: kafka streams service which tracks the set of connected client_ids
- DEAD ZONE MONITOR:  when the set reaches size 0 *and* when a sufficient amount of time has passed, *then* shut down the big-box container host instance
- DEAD ZONE MONITOR: _prior to shutdown_, emit a message via kafka.  this will let gateway know to disconnect
- REMOTE CONTROL capabilities need to be created
- REMOTE CONTROL should be its own service, isolated from gateway
- REMOTE CONTROL accepts a single command: _*TURN ON THE BIG BOX*_
- use rusoto for aws ec2 control
- rusoto can query via instance tags to figure out private DNS of giant container host
- Sabaki ONLY connects to gateway
- Above approach isolates  such that Sabaki doesn't have to know _anything_ about REMOTE CONTROL. 

#### Redis pub/sub approach 

- Gateway pushes ACTIVITY message here 
- ALARM CLOCK is keeping its own state on whether system is alive. If not, wake it up on ACTIVITY 
- ALARM CLOCK pushes IT'S ONLINE NOW when system is up
- Gateway reestablishes Kafka connection when system comes up 

#### UDP approach

- this isn't quite right - amend 
- gateway fires and forgets `enum RemoteControlCommands{ Off, On }`
- use [tokio udp](
https://docs.rs/tokio/0.1.22/tokio/net/udp/index.html) for one way send from gateway to RC 📺 
- Gateway can listen for private DNS of the freshly-initialized big-box over a UDP connection

#### HTTP approach

- Just use rocket for remote control API layer
- Use request/response.  Remote control provides private DNS of giant host instance as the result of a `POST /rc/on` command

---

## Tasks

- finalize machine split
- implement SHUTDOWN 📴 service 
- implement ALARM CLOCK 🕒 service
- gateway graceful Kafka disconn
- gateway communication with ALARM CLOCK
- gateway management of existing commands. Don't change the flow drastically , just queue up FindGame /Create Game / Join Private / Choose Color Pref and execute them after  system boots
- Sabaki notification that system is booting  
- Gateway listens to Redis topic for system Liveness heartbeat, driven by ALARM CLOCK. Gateway state mirrors that value (once per sec heartbeat 💓
- Redis for gateway to track queue of delayed commands

**Comment by Terkwood** [comment]
Need to solve #95 before taking on this issue

**Comment by Terkwood** [comment]
We don't need a Kafka streams app to track Liveness of the system. Just a rust app which uses rdkafka and keeps a count in memory.

**Comment by Terkwood** [comment]
https://docs.rs/rusoto_ec2/0.40.0/rusoto_ec2/struct.StopInstancesRequest.html

**Comment by Terkwood** [comment]
[Rusoto doc for the ec2 private DNS name of an instance](https://rusoto.github.io/rusoto/rusoto_ec2/struct.Instance.html#structfield.private_dns_name)

**Comment by Terkwood** [comment]
Let's try to fit Kafka in the smaller instance so that we don't have to manage disconnection in gateway. Also would allow communication between `bugle` and `gateway` over Kafka

**Comment by Terkwood** [comment]
https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html

**Comment by Terkwood** [comment]
https://coreos.com/os/docs/latest/customizing-docker.html

**Comment by Terkwood** [comment]
https://coreos.com/os/docs/latest/mounting-storage.html

**Comment by Terkwood** [comment]
https://gist.github.com/Terkwood/7a01ad35f500934baf4da8a9dd2f8767

**Comment by Terkwood** [comment]
https://github.com/coreos/docs/blob/master/os/getting-started-with-systemd.md

**Comment by Terkwood** [comment]
https://github.com/confluentinc/kafka-streams-examples/issues/180

**Comment by Terkwood** [comment]
https://docs.confluent.io/current/streams/faq.html#interactive-queries

**Comment by Terkwood** [comment]
```
thread '<unnamed>' panicked at 'Nested error (!) waiting on kafka stream: KafkaError (Message consumption error: GroupLoadInProgress (Broker: Group coordinator load in progress))', src/kafka_io.rs:111:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'Unable to receive kafka event via router channel: RecvError', src/router.rs:275:29
```

**Comment by Terkwood** [comment]
```json
1574821076618:{"secs_since_epoch":1574821076,"nanos_since_epoch":618310524}
```

**Comment by Terkwood** [comment]
https://github.com/tokio-rs/tokio/blob/master/examples/echo-udp.rs

**Comment by Terkwood** [comment]
Since we plan to [make gateway stateless](https://github.com/Terkwood/BUGOUT/issues/134) using Redis, it seems reasonable to use Redis for pub sub to bugle /startup service

**Comment by Terkwood** [comment]
https://docs.rs/redis/0.13.0/redis/struct.Connection.html#method.is_open

**Comment by Terkwood** [comment]
https://github.com/sfackler/r2d2

**Comment by Terkwood** [comment]
Hopefully we don't need this, but:  rusoto doc for private DNS name of an instance 

https://rusoto.github.io/rusoto/rusoto_ec2/struct.Instance.html#structfield.private_dns_name

**Comment by Terkwood** [comment]
https://stackoverflow.com/questions/35878270/docker-redis-container-getting-warning-proc-sys-net-core-somaxconn-in-a-user-d
