### ISSUE TITLE
☕️ JVM services: Kafka InvalidPidMappingException

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#89]
# System stops processing moves

This exception was seen in multiple services.

_Gateway_ service showed no errors at all

## History provider

```text
📚          ️d026ae80 HISTPROV HistoryProvided(gameId=d026ae80-a7e1-40a3-8e02-d297bf611d5e, replyTo=d8469f2b-9238-45af-94e0-7b23004fbf0d, eventId=425fbe0e-f9c4-4e98-8b30-a233feac61b0, moves=[], epochMillis=1566684125177)
Exception in thread "bugout-history-provider-48398a94-7ebb-4572-98cd-3958b1e152a8-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: task [0_0] Abort sending since an error caught with a previous record (key d026ae80-a7e1-40a3-8e02-d297bf611d5e value {"type":"HistoryProvided","gameId":"d026ae80-a7e1-40a3-8e02-d297bf611d5e","replyTo":"d8469f2b-9238-45af-94e0-7b23004fbf0d","eventId":"425fbe0e-f9c4-4e98-8b30-a233feac61b0","moves":[],"epochMillis":1566684125177} timestamp 1566684124980) to topic bugout-history-provided-ev due to org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.recordSendError(RecordCollectorImpl.java:138)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.access$500(RecordCollectorImpl.java:50)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl$1.onCompletion(RecordCollectorImpl.java:201)
	at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:1318)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:230)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.abort(ProducerBatch.java:158)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortBatches(RecordAccumulator.java:742)
	at org.apache.kafka.clients.producer.internals.Sender.maybeAbortBatches(Sender.java:479)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.
	at org.apache.kafka.clients.producer.internals.TransactionManager$AddPartitionsToTxnHandler.handleResponse(TransactionManager.java:1204)
	at org.apache.kafka.clients.producer.internals.TransactionManager$TxnRequestHandler.onComplete(TransactionManager.java:1069)
	at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:561)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:553)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:307)
	... 2 more
Caused by: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.
```

## Judge

```text
⚖️          ️d026ae80 ACCEPT   BLACK @ Coord(x=14, y=13) capturing
Exception in thread "bugout-judge-17432a73-0993-4717-b94d-ba7218e9e859-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: task [0_0] Abort sending since an error caught with a previous record (key d026ae80-a7e1-40a3-8e02-d297bf611d5e value {"type":"MoveMade","gameId":"d026ae80-a7e1-40a3-8e02-d297bf611d5e","replyTo":"bc148b87-04f0-49f0-bfc5-d135d3453bb6","eventId":"f7d635d9-f7c1-4602-bf37-ab375f4dd266","player":"BLACK","coord":{"x":14,"y":13},"captured":[]} timestamp 1566684102451) to topic bugout-move-accepted-ev due to org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.recordSendError(RecordCollectorImpl.java:138)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.access$500(RecordCollectorImpl.java:50)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl$1.onCompletion(RecordCollectorImpl.java:201)
	at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:1310)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:230)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.abort(ProducerBatch.java:158)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortBatches(RecordAccumulator.java:742)
	at org.apache.kafka.clients.producer.internals.Sender.maybeAbortBatches(Sender.java:460)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:297)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:235)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.
	at org.apache.kafka.clients.producer.internals.TransactionManager$AddPartitionsToTxnHandler.handleResponse(TransactionManager.java:1041)
	at org.apache.kafka.clients.producer.internals.TransactionManager$TxnRequestHandler.onComplete(TransactionManager.java:909)
	at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:557)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:549)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:288)
	... 2 more
Caused by: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.
```

**Comment by Terkwood** [comment]
Haven't seen this for a long time
